import type { Metadata } from 'next'
import { Faster_One, Inter } from 'next/font/google'
import './globals.css'
import HeadNavbar from '@/components/Auto/UI/HeadNavbar'
import Footer from '@/components/Auto/UI/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  robots: {
    index: false
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeadNavbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
